export interface FlourData {
  name: string;
  brand: string;
  type: string;
  protein: string;
  protein_value: number;
  strength_w: string;
  w_value: number;
  hydration: string;
  hydration_default: number;
  hydration_max: number;
  hydration_min: number;
  fermentation_hours: string;
  fermentation_min: number;
  fermentation_max: number;
  fermentation_type: string[];
  description: string;
  recommended_styles: string[];
  secondary_styles: string[];
  not_ideal_for: string[];
  style_scores: Record<string, number>;
}

export const FLOURS: FlourData[] = [
  {
    name: 'Caputo Pizzeria 00',
    brand: 'Caputo',
    type: '00',
    protein: '12.5%',
    protein_value: 12.5,
    strength_w: 'W260–280',
    w_value: 270,
    hydration: '55–65%',
    hydration_default: 60,
    hydration_max: 65,
    hydration_min: 55,
    fermentation_hours: '8–24',
    fermentation_min: 8,
    fermentation_max: 24,
    fermentation_type: ['room_temp', 'short_cold'],
    description: 'Classic Neapolitan pizza flour with balanced elasticity.',
    recommended_styles: ['Neapolitan'],
    secondary_styles: ['New York'],
    not_ideal_for: ['Neo Neapolitan', 'Detroit', 'Sicilian'],
    style_scores: { Neapolitan: 5, 'Neo Neapolitan': 2, 'New York': 3, Roman: 3, Brooklyn: 2, Detroit: 1, Sicilian: 1 },
  },
  {
    name: 'Caputo Nuvola',
    brand: 'Caputo',
    type: '0',
    protein: '12.5%',
    protein_value: 12.5,
    strength_w: 'W270–310',
    w_value: 290,
    hydration: '65–75%',
    hydration_default: 70,
    hydration_max: 75,
    hydration_min: 65,
    fermentation_hours: '24–72',
    fermentation_min: 24,
    fermentation_max: 72,
    fermentation_type: ['cold_ferment', 'room_temp'],
    description: 'High hydration flour for airy, open crumb pizza — ideal for contemporary Neapolitan styles.',
    recommended_styles: ['Neo Neapolitan'],
    secondary_styles: ['Neapolitan', 'Roman'],
    not_ideal_for: ['Detroit'],
    style_scores: { Neapolitan: 3, 'Neo Neapolitan': 5, 'New York': 3, Roman: 4, Brooklyn: 3, Detroit: 2, Sicilian: 2 },
  },
  {
    name: 'Caputo Manitoba Oro',
    brand: 'Caputo',
    type: '0',
    protein: '14.5%',
    protein_value: 14.5,
    strength_w: 'W350–400',
    w_value: 370,
    hydration: '70–80%',
    hydration_default: 72,
    hydration_max: 80,
    hydration_min: 70,
    fermentation_hours: '48–96',
    fermentation_min: 48,
    fermentation_max: 96,
    fermentation_type: ['long_cold'],
    description: 'Very strong flour for long fermentation and high hydration.',
    recommended_styles: ['New York', 'Detroit', 'Sicilian'],
    secondary_styles: ['Roman', 'Neo Neapolitan'],
    not_ideal_for: ['Neapolitan'],
    style_scores: { Neapolitan: 1, 'Neo Neapolitan': 3, 'New York': 5, Roman: 4, Brooklyn: 4, Detroit: 5, Sicilian: 5 },
  },
  {
    name: 'Pivetti Tipo 00',
    brand: 'Pivetti',
    type: '00',
    protein: '12%',
    protein_value: 12,
    strength_w: 'W240–280',
    w_value: 260,
    hydration: '55–65%',
    hydration_default: 60,
    hydration_max: 65,
    hydration_min: 55,
    fermentation_hours: '12–36',
    fermentation_min: 12,
    fermentation_max: 36,
    fermentation_type: ['room_temp', 'cold_ferment'],
    description: 'Balanced Italian flour for classic pizza dough.',
    recommended_styles: ['Neapolitan', 'Roman'],
    secondary_styles: ['New York'],
    not_ideal_for: ['Neo Neapolitan', 'Detroit'],
    style_scores: { Neapolitan: 5, 'Neo Neapolitan': 2, 'New York': 3, Roman: 4, Brooklyn: 3, Detroit: 1, Sicilian: 2 },
  },
  {
    name: 'Shtybel 2 Bread Flour',
    brand: 'Shtybel',
    type: 'Bread Flour',
    protein: '12%',
    protein_value: 12,
    strength_w: 'W260–300',
    w_value: 280,
    hydration: '60–70%',
    hydration_default: 65,
    hydration_max: 70,
    hydration_min: 60,
    fermentation_hours: '12–48',
    fermentation_min: 12,
    fermentation_max: 48,
    fermentation_type: ['room_temp', 'cold_ferment'],
    description: 'Versatile bread flour commonly used for NY-style pizza.',
    recommended_styles: ['New York', 'Brooklyn'],
    secondary_styles: ['Sicilian'],
    not_ideal_for: ['Neapolitan'],
    style_scores: { Neapolitan: 2, 'Neo Neapolitan': 3, 'New York': 5, Roman: 3, Brooklyn: 5, Detroit: 4, Sicilian: 4 },
  },
  {
    name: 'Shtybel 15',
    brand: 'Shtybel',
    type: 'Strong Bread',
    protein: '13.5%',
    protein_value: 13.5,
    strength_w: 'W300–350',
    w_value: 325,
    hydration: '65–75%',
    hydration_default: 68,
    hydration_max: 75,
    hydration_min: 65,
    fermentation_hours: '24–72',
    fermentation_min: 24,
    fermentation_max: 72,
    fermentation_type: ['cold_ferment', 'long_cold'],
    description: 'Strong Israeli bread flour with high protein for long cold fermentation and thick-crust styles.',
    recommended_styles: ['Detroit', 'Sicilian'],
    secondary_styles: ['Neo Neapolitan', 'New York', 'Brooklyn'],
    not_ideal_for: ['Neapolitan'],
    style_scores: { Neapolitan: 1, 'Neo Neapolitan': 4, 'New York': 4, Roman: 3, Brooklyn: 4, Detroit: 5, Sicilian: 5 },
  },
  {
    name: 'Shtybel Pizza & Focaccia',
    brand: 'Shtybel',
    type: 'Pizza/Focaccia',
    protein: '12%',
    protein_value: 12,
    strength_w: 'W230–270',
    w_value: 250,
    hydration: '60–72%',
    hydration_default: 65,
    hydration_max: 72,
    hydration_min: 60,
    fermentation_hours: '8–36',
    fermentation_min: 8,
    fermentation_max: 36,
    fermentation_type: ['room_temp', 'cold_ferment'],
    description: 'Purpose-built Israeli flour for pizza and focaccia — soft crumb with a crispy base.',
    recommended_styles: ['Roman', 'Neapolitan'],
    secondary_styles: ['Brooklyn', 'New York'],
    not_ideal_for: ['Neo Neapolitan', 'Detroit'],
    style_scores: { Neapolitan: 4, 'Neo Neapolitan': 2, 'New York': 3, Roman: 5, Brooklyn: 3, Detroit: 2, Sicilian: 3 },
  },
  {
    name: 'Shtybel Pizza',
    brand: 'Shtybel',
    type: '00',
    protein: '14%',
    protein_value: 14,
    strength_w: 'W360',
    w_value: 360,
    hydration: '62–72%',
    hydration_default: 66,
    hydration_max: 72,
    hydration_min: 62,
    fermentation_hours: '24–72',
    fermentation_min: 24,
    fermentation_max: 72,
    fermentation_type: ['cold_ferment'],
    description: 'Strong Israeli pizza flour (W360 "00") — designed for cold fermented Italian-style pizza and focaccia with 24–72h in the fridge.',
    recommended_styles: ['Neapolitan', 'New York'],
    secondary_styles: ['Neo Neapolitan', 'Roman'],
    not_ideal_for: ['Detroit', 'Sicilian'],
    style_scores: { Neapolitan: 5, 'Neo Neapolitan': 3, 'New York': 4, Roman: 4, Brooklyn: 3, Detroit: 2, Sicilian: 2 },
  },
  {
    name: 'Shtybel Raananis',
    brand: 'Shtybel',
    type: '00',
    protein: '14.5%',
    protein_value: 14.5,
    strength_w: 'W360',
    w_value: 360,
    hydration: '65–75%',
    hydration_default: 70,
    hydration_max: 75,
    hydration_min: 65,
    fermentation_hours: '48–96',
    fermentation_min: 48,
    fermentation_max: 96,
    fermentation_type: ['long_cold'],
    description: 'Premium Israeli W360 "00" pizza flour, developed with pizza expert Raanan Yosef Nosel — built for 48–96h cold fermentation and a deeply flavoured, airy crust.',
    recommended_styles: ['Neapolitan', 'Neo Neapolitan'],
    secondary_styles: ['Roman', 'New York'],
    not_ideal_for: ['Detroit', 'Sicilian'],
    style_scores: { Neapolitan: 5, 'Neo Neapolitan': 4, 'New York': 3, Roman: 4, Brooklyn: 3, Detroit: 1, Sicilian: 2 },
  },
  {
    name: 'Caputo Nuvola Super',
    brand: 'Caputo',
    type: '0',
    protein: '14.5%',
    protein_value: 14.5,
    strength_w: 'W340–380',
    w_value: 360,
    hydration: '70–80%',
    hydration_default: 75,
    hydration_max: 80,
    hydration_min: 70,
    fermentation_hours: '48–120',
    fermentation_min: 48,
    fermentation_max: 120,
    fermentation_type: ['long_cold'],
    description: 'Stronger version of Nuvola for very high hydration and extended cold fermentation — delivers an ultra-light, airy crumb.',
    recommended_styles: ['Neo Neapolitan', 'Roman'],
    secondary_styles: ['Brooklyn'],
    not_ideal_for: ['Neapolitan', 'Detroit'],
    style_scores: { Neapolitan: 1, 'Neo Neapolitan': 5, 'New York': 3, Roman: 5, Brooklyn: 4, Detroit: 2, Sicilian: 3 },
  },
  {
    name: 'Shtybel Manitoba',
    brand: 'Shtybel',
    type: 'Manitoba',
    protein: '17.5%',
    protein_value: 17.5,
    strength_w: 'W340+',
    w_value: 370,
    hydration: '70–82%',
    hydration_default: 75,
    hydration_max: 82,
    hydration_min: 70,
    fermentation_hours: '48–120',
    fermentation_min: 48,
    fermentation_max: 120,
    fermentation_type: ['long_cold'],
    description: 'Very high-protein Israeli Manitoba flour from Canadian wheat — use pure for ultra-high hydration doughs, or blend up to 30% with a weaker flour to boost strength for extended cold fermentation.',
    recommended_styles: ['Detroit', 'Sicilian'],
    secondary_styles: ['Neo Neapolitan', 'Roman', 'Brooklyn'],
    not_ideal_for: ['Neapolitan'],
    style_scores: { Neapolitan: 1, 'Neo Neapolitan': 4, 'New York': 3, Roman: 4, Brooklyn: 4, Detroit: 5, Sicilian: 5 },
  },
  {
    name: 'Caputo Classica 00',
    brand: 'Caputo',
    type: '00',
    protein: '12%',
    protein_value: 12,
    strength_w: 'W220–240',
    w_value: 230,
    hydration: '55–65%',
    hydration_default: 60,
    hydration_max: 65,
    hydration_min: 55,
    fermentation_hours: '4–18',
    fermentation_min: 4,
    fermentation_max: 18,
    fermentation_type: ['room_temp'],
    description: 'Light all-purpose Italian 00 flour — ideal for quick same-day doughs, everyday pizza, and soft bread.',
    recommended_styles: ['Neapolitan', 'Roman'],
    secondary_styles: ['New York'],
    not_ideal_for: ['Neo Neapolitan', 'Detroit', 'Sicilian'],
    style_scores: { Neapolitan: 3, 'Neo Neapolitan': 1, 'New York': 3, Roman: 3, Brooklyn: 2, Detroit: 1, Sicilian: 1 },
  },
  {
    name: 'Caputo Chef 00',
    brand: 'Caputo',
    type: '00',
    protein: '13.5%',
    protein_value: 13.5,
    strength_w: 'W300–320',
    w_value: 310,
    hydration: '63–70%',
    hydration_default: 66,
    hydration_max: 70,
    hydration_min: 63,
    fermentation_hours: '24–48',
    fermentation_min: 24,
    fermentation_max: 48,
    fermentation_type: ['cold_ferment'],
    description: 'Professional Italian 00 flour (red Cuoco bag) — strong and elastic, built for cold-fermented Neapolitan and New York style pizza with outstanding extensibility.',
    recommended_styles: ['Neapolitan', 'New York'],
    secondary_styles: ['Neo Neapolitan', 'Brooklyn'],
    not_ideal_for: ['Detroit', 'Sicilian'],
    style_scores: { Neapolitan: 5, 'Neo Neapolitan': 3, 'New York': 5, Roman: 4, Brooklyn: 4, Detroit: 2, Sicilian: 2 },
  },
  {
    name: 'Spadoni PZ2',
    brand: 'Molino Spadoni',
    type: '00',
    protein: '11%',
    protein_value: 11,
    strength_w: 'W200',
    w_value: 200,
    hydration: '55–62%',
    hydration_default: 58,
    hydration_max: 62,
    hydration_min: 55,
    fermentation_hours: '4–8',
    fermentation_min: 4,
    fermentation_max: 8,
    fermentation_type: ['room_temp'],
    description: 'Italian 00 pizza flour for soft, traditional pizza — designed for quick same-day rising (4–8h), simple and approachable.',
    recommended_styles: ['Neapolitan', 'Roman'],
    secondary_styles: ['New York'],
    not_ideal_for: ['Neo Neapolitan', 'Detroit', 'Sicilian'],
    style_scores: { Neapolitan: 4, 'Neo Neapolitan': 1, 'New York': 3, Roman: 3, Brooklyn: 2, Detroit: 1, Sicilian: 1 },
  },
  {
    name: 'Spadoni PZ4',
    brand: 'Molino Spadoni',
    type: '00',
    protein: '12.5%',
    protein_value: 12.5,
    strength_w: 'W320–350',
    w_value: 335,
    hydration: '58–68%',
    hydration_default: 62,
    hydration_max: 68,
    hydration_min: 58,
    fermentation_hours: '8–20',
    fermentation_min: 8,
    fermentation_max: 20,
    fermentation_type: ['room_temp', 'cold_ferment'],
    description: 'Italian 00 "Croccante" pizza flour — strong gluten for medium-long fermentation yielding a crispy, well-charred crust.',
    recommended_styles: ['New York', 'Brooklyn'],
    secondary_styles: ['Neapolitan', 'Roman'],
    not_ideal_for: ['Neo Neapolitan', 'Sicilian'],
    style_scores: { Neapolitan: 3, 'Neo Neapolitan': 2, 'New York': 5, Roman: 3, Brooklyn: 5, Detroit: 3, Sicilian: 2 },
  },
  {
    name: 'Spadoni Manitoba XLL',
    brand: 'Molino Spadoni',
    type: 'Manitoba',
    protein: '14.5%',
    protein_value: 14.5,
    strength_w: 'W380+',
    w_value: 400,
    hydration: '70–82%',
    hydration_default: 75,
    hydration_max: 82,
    hydration_min: 70,
    fermentation_hours: '48–120',
    fermentation_min: 48,
    fermentation_max: 120,
    fermentation_type: ['long_cold'],
    description: 'Ultra-strong Italian Manitoba 0 flour — for very high hydration doughs and long cold fermentation, or as a 20–30% blend to reinforce weaker flour.',
    recommended_styles: ['Detroit', 'Sicilian'],
    secondary_styles: ['Neo Neapolitan', 'Roman', 'Brooklyn'],
    not_ideal_for: ['Neapolitan'],
    style_scores: { Neapolitan: 1, 'Neo Neapolitan': 4, 'New York': 3, Roman: 4, Brooklyn: 4, Detroit: 5, Sicilian: 5 },
  },
  {
    name: 'Kemah HaAretz Pizza 00 Quick',
    brand: 'Kemah HaAretz',
    type: '00',
    protein: '13%',
    protein_value: 13,
    strength_w: 'W230–250',
    w_value: 240,
    hydration: '55–65%',
    hydration_default: 60,
    hydration_max: 65,
    hydration_min: 55,
    fermentation_hours: '2–8',
    fermentation_min: 2,
    fermentation_max: 8,
    fermentation_type: ['room_temp'],
    description: 'Israeli Tipo 00 pizza flour (imported from Italy) for quick same-day doughs — 13% protein at W230–250.',
    recommended_styles: ['Neapolitan', 'Roman'],
    secondary_styles: ['New York'],
    not_ideal_for: ['Neo Neapolitan', 'Detroit', 'Sicilian'],
    style_scores: { Neapolitan: 4, 'Neo Neapolitan': 1, 'New York': 3, Roman: 4, Brooklyn: 2, Detroit: 1, Sicilian: 1 },
  },
  {
    name: 'Kemah HaAretz Pizza 00 Long',
    brand: 'Kemah HaAretz',
    type: '00',
    protein: '14%',
    protein_value: 14,
    strength_w: 'W300–320',
    w_value: 310,
    hydration: '62–72%',
    hydration_default: 66,
    hydration_max: 72,
    hydration_min: 62,
    fermentation_hours: '36–72',
    fermentation_min: 36,
    fermentation_max: 72,
    fermentation_type: ['cold_ferment', 'long_cold'],
    description: 'Israeli Tipo 00 pizza flour (imported from Italy) for long cold fermentation — W300–320 at 14% protein, delivers complex flavour and open, airy crumb.',
    recommended_styles: ['Neapolitan', 'New York'],
    secondary_styles: ['Neo Neapolitan', 'Roman'],
    not_ideal_for: ['Detroit', 'Sicilian'],
    style_scores: { Neapolitan: 5, 'Neo Neapolitan': 3, 'New York': 4, Roman: 4, Brooklyn: 3, Detroit: 2, Sicilian: 2 },
  },
  {
    name: 'Kemah HaAretz Pizza & Focaccia',
    brand: 'Kemah HaAretz',
    type: '00',
    protein: '12%',
    protein_value: 12,
    strength_w: 'W240–280',
    w_value: 260,
    hydration: '58–70%',
    hydration_default: 63,
    hydration_max: 70,
    hydration_min: 58,
    fermentation_hours: '8–36',
    fermentation_min: 8,
    fermentation_max: 36,
    fermentation_type: ['room_temp', 'cold_ferment'],
    description: 'Israeli 00 pizza and focaccia flour from Kemah HaAretz — versatile medium-strength flour for classic pizza styles and high-hydration focaccia.',
    recommended_styles: ['Roman', 'Neapolitan'],
    secondary_styles: ['New York', 'Brooklyn'],
    not_ideal_for: ['Neo Neapolitan', 'Detroit'],
    style_scores: { Neapolitan: 4, 'Neo Neapolitan': 2, 'New York': 3, Roman: 5, Brooklyn: 3, Detroit: 1, Sicilian: 2 },
  },
];
